# Same as '--severity'
# Default is all severities
severity:
  - HIGH
  - CRITICAL

scan:
  # Same as '--security-checks'
  # Default depends on subcommand
  security-checks:
    - vuln

vulnerability:
  # Same as '--vuln-type'
  # Default is 'os,library'
  type:
    - library

# Same as '--format'
format: sarif

# Same as '--output'
# Used to upload sarif to GitHub Security tab
output: trivy-results.sarif

# Same as '--ignore-unfixed'
ignore-unfixed: false

# Same as '--list-all-pkgs'
list-all-pkgs: false

# Same as '--exit-code'
# Zero as we are only reporting for now, not enforcing
exit-code: 0

timeout: 30m

output: 'trivy-results.sarif'
